import '../styles/globals.css'
import type { AppProps } from 'next/app'

import { SessionProvider } from 'next-auth/react';

import Head from 'next/head'
import Navigation from '../components/Navigation'

export default function App({ Component, pageProps: {session, ...pageProps} }: AppProps) {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <SessionProvider session={session}>
      <Navigation />
      <div className="pt-12"></div>
      <Component {...pageProps} />
    </SessionProvider>
  </>
}
